### ISSUE TITLE
update links to legacy weisslab

### ISSUE THREAD

**Issue by YipengHu** [YipengHu/MPHY0043#15]
Affected file:

- [x] tutorials/gesture/download_data

**Comment by MOYF-beta** [comment]
```
https://weisslab.cs.ucl.ac.uk/WEISSTeaching/datasets/-/raw/jigsaws/video-meta.zip
```
this link in the gesture download script is still unable to access, and accessing domain `http://weisslab.cs.ucl.ac.uk/` also throws overtime error.
